---
- name: pulling image
  hosts: QASERVER
  tasks:
   - name: pulling image
     command: docker pull krishna1654/http1
   - name: running image
     command: docker run --name v1 -d -p 8010:80 krishna1654/http1
...
